language: node_js

node_js:
  - 9.0

sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install sbt;
      brew tap tcnksm/ghr;
      brew install ghr;
    else
      sudo apt-get install -y fakeroot;
      curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme;
      chmod +x ~/bin/gimme;
      go get -u github.com/tcnksm/ghr; 
    fi

before_script:
  - npm install -g yarn
  - yarn

script:
  - yarn build
  - yarn test


# We explicitly set the matrix
matrix:
  include:
    - os: osx
      osx_image: xcode8


after_success:
  - sh deploy.sh